#import "../../macros.typ": *

== Verification Frontends and Prusti <sec:bg-prusti>

Viper's intermediate language is a target rather than a source. A frontend takes a program in some high-level language and produces a Viper program whose verification establishes the property the frontend cares about. Prusti @prusti does this for Rust, Nagini @nagini for Python, Gobra @gobra for Go, and VerCors @vercors for Java. What they share is the hard part of the translation: each has to express its source language's memory model in Viper permissions, so that holding a permission in the encoded program corresponds to being allowed to touch the memory in the original one.

The obligations a frontend produces fall into two groups, and the split is by who writes them. A _functional specification_ is written by a person and states what the program computes. It is an arbitrary first-order assertion, and proving one may take arithmetic, quantifiers and rich theories. The _core proof_ is generated by the frontend, and it is the set of obligations that result from encoding the source language's memory and ownership semantics: that a permission is held wherever memory is accessed, that ownership transfers correctly across a call boundary, and that a structure's invariant is re-established before it is handed on. The distinction is visible in what Prusti does with an unannotated program: it still emits the full encoding of the obligations that follow from Rust's memory model, and there is simply no functional specification alongside them.

Rust makes the core proof interesting to us. Its type system enforces that a value is either shared or mutable but never both, and the borrow checker establishes this statically, before verification begins. Prusti therefore derives the whole core proof from the program source and Rust's semantics @prusti-oopsla, with no annotation from the programmer. Python, Go and Java carry no such ownership discipline, so a Nagini, Gobra or VerCors user writes the permission structure by hand as part of the specification. Prusti is consequently the only frontend that produces the workload this thesis targets: a large, highly structured set of obligations from a program that says nothing about what it computes.

The rest of this section takes the Rust constructs one at a time and gives the
Viper each becomes. No example below carries a specification, so everything
shown follows from Rust's semantics alone. Identifiers are shortened throughout
to improve readability.

#para[Scalars] A built-in scalar becomes four declarations: a domain giving the
type its values, a field and a predicate giving it a place in the heap, and a
function reading the one out of the other.

#viper(
  caption: [The declarations Prusti emits for #ru[`i32`]. #vi[`bool`] and the
    unit type follow the same pattern.],
  label: "lst:prusti-scalar",
  placement: auto,
)[```viper
domain i32 {
  function i32_cons(v: Int): i32
  function i32_value(s: i32): Int

  axiom { forall s: i32 :: {i32_value(s)}
    i32_cons(i32_value(s)) == s }
  axiom { forall s: i32 :: {i32_value(s)}
    -2147483648 <= i32_value(s) && i32_value(s) <= 2147483647 }
}

field p_i32_val: i32
predicate p_i32(self: Ref) { acc(self.p_i32_val, write) }

function p_i32_snap(self: Ref): i32
  requires acc(p_i32(self), write)
```]

The domain is the value. #vi[`i32_cons`] and #vi[`i32_value`] convert between a
snapshot and the integer behind it, and the axioms state that the two are
inverse and that the value stays inside the type's range. Every axiom carries a
trigger the encoder writes. The predicate is the permission, and #vi[`p_i32_snap`] bridges the two,
reading the field out from under the predicate with an #vi[`unfolding`]. The
encoding can therefore speak of a value wherever it holds the permission. A
companion method #vi[`p_i32_assign`] is bodyless, and its postcondition grants
the predicate at a given value. The encoding writes a local by calling it.

Arithmetic is a function over snapshots rather than an operation in a method
body. Prusti emits one per operator and operand type, and an operator that can
overflow returns the result paired with a flag. So #ru[`a + b`] becomes an
application of #vi[`add_ovf_i32`], which wraps the sum into range and reports
whether the wrap changed it.

#para[Structs and enums] A struct becomes an algebraic data type for its values
and a predicate for its permissions. The predicate holds one permission per
field, reached through a function from the struct's reference to the field's.
An enum adds a discriminant.

#lowering(
  caption: [An enum becomes one constructor per variant, a predicate over the
    discriminant, and one predicate per variant carrying that variant's
    payload.],
  label: "lst:prusti-enum",
  source-lang: "rust",
  target-lang: "viper",
  stacked: true,
  placement: auto,
)[```rust
enum Shape {
  Circle(i32),
  Rect(i32, i32),
}
```][```viper
adt Shape {
  Shape_0_cons(f0: i32)
  Shape_1_cons(f0: i32, f1: i32)
}

predicate p_Shape(self: Ref) {
  acc(p_isize(Shape_discr(self)), write) &&
  (let d == (p_isize_snap(Shape_discr(self))) in
    (d == isize_cons(0) || d == isize_cons(1)) &&
    (d == isize_cons(0) ==>
      acc(p_Shape_0(self), write)) &&
    (d == isize_cons(1) ==>
      acc(p_Shape_1(self), write)))
}
```]

One #vi[`p_Shape_N`] predicate per variant holds that variant's payload. The
disjunction states that the two variants exhaust the type, and each payload
permission is guarded by the discriminant that selects it. A program holding
#vi[`p_Shape`] therefore holds the payload of exactly one variant. Reading a value back
out reverses that structure: the snapshot function tests the discriminant, and
under each test unfolds the matching variant's predicate and applies that
variant's constructor.

#block(breakable: false, no-numbers[```viper
function p_Shape_snap(self: Ref): Shape
  requires acc(p_Shape(self), write)
{ unfolding acc(p_Shape(self), write) in
    d == isize_cons(1)
      ? unfolding acc(p_Shape_1(self), write) in Shape_1_cons(...)
  : d == isize_cons(0) ? ...
  : Shape_unreachable() }
```])


#para[Rust functions] A function becomes a method whose return value is an
output parameter. The parameters are references, the precondition holds the
predicates of the arguments, and the postcondition holds the predicate of the
result.

#lowering(
  caption: [The signature Prusti emits for a two-argument function. Prusti names
    the parameters after the MIR locals, which are renamed here to match the
    Rust.],
  label: "lst:prusti-signature",
  source-lang: "rust",
  target-lang: "viper",
  placement: auto,
)[```rust
fn add(a: i32,
       b: i32) -> i32
```][```viper
method add(res: Ref, a: Ref, b: Ref)
  requires acc(p_i32(a), write)
  requires acc(p_i32(b), write)
  ensures acc(p_i32(res), write)
```]

The body is a flat graph: one #vi[`label`] per basic block, reached by
#vi[`goto`], and one Boolean per edge of that graph, set to #vi[`false`] at
entry and to #vi[`true`] on the edge taken. A block reachable from several
predecessors reads those booleans back to recover which way control arrived, so
its heap operations are guarded by the path reaching it. A block Prusti knows to
be unreachable, such as the one a panic would enter, contains an
#vi[`assert false`].

#para[Branching] An #ru[`if`] and a #ru[`match`] are expressions in Rust, and
one written for its effect rather than its value is an expression of type
#ru[`()`]. The encoding keeps
that view: both forms produce the same shape, and they differ only in what the
arms assign.

#lowering(
  caption: [A conditional used for its effect. Each arm assigns the unit value
    to the result, and the second arm guards its heap operations with the edge
    it arrived on.],
  label: "lst:prusti-if",
  source-lang: "rust",
  target-lang: "viper",
  stacked: true,
  placement: none,
)[```rust
fn maybe(b: bool, p: &mut i32) {
  if b { *p = 1; }
}
```][```viper
label bb_0
if (bool_value(b_val) == false) {
  from_bb0_to_bb2 := true
  goto bb_2
} else {
  from_bb0_to_bb1 := true
  goto bb_1
}

label bb_2
p_Unit_assign(res, Unit_cons())
goto bb_3

label bb_1
if (from_bb0_to_bb1) { make_concrete_i32(deref_p) }
p_i32_assign(deref_p, i32_cons(1))
p_Unit_assign(res, Unit_cons())
goto bb_3
```]

The method carries #vi[`ensures acc(p_Unit(res), write)`], so the unit a Rust
conditional evaluates to is a heap value it has to produce. Both arms produce
it. A conditional used for its value differs only in assigning an
#vi[`i32`] instead. A #ru[`match`] dispatches the same way, on the discriminant
it has read out of the enum.

That makes exhaustiveness an obligation about producing a value. Every arm the
compiler considers live constructs the result. The arm that no variant selects
constructs nothing and does #vi[`exhale false`] instead, discharging its
obligation by proving the path unreachable rather than by building the value it
would owe.

#para[Generics] The encoding reifies Rust's types into values and erases every
generic position to a single opaque type, so no Viper type parameter appears
anywhere.

#lowering(
  caption: [A generic struct. The type parameter becomes an ordinary value
    argument of type #vi[`Type`], and the field holds the erased snapshot
    #vi[`Param`].],
  label: "lst:prusti-generic",
  source-lang: "rust",
  target-lang: "viper",
  stacked: true,
)[```rust
struct Wrap<T> { inner: T }

fn unwrap_it<T>(w: Wrap<T>) -> T {
  w.inner
}
```][```viper
adt Type { i32_type() bool_type() }
domain Param { }

predicate p_Param(self: Ref, T: Type)

predicate p_Wrap(self: Ref, T: Type) {
  acc(p_Param(Wrap_field_0(self, T), T), write)
}

method unwrap_it(res: Ref, w: Ref, T: Type)
  requires acc(p_Wrap(w, T), write)
  ensures acc(p_Param(res, T), write)
```]

A value whose type is a parameter has the snapshot type #vi[`Param`], a domain
without functions or axioms. Its permission is #vi[`p_Param`], an abstract
predicate taking the reified type beside the reference. Crossing
between a concrete type and its erased form takes a cast, and the encoding
provides one at each level. On values, a pair of bodyless functions converts a
snapshot in each direction, each naming the other in its postcondition.

#no-numbers[```viper
function generic_i32(self: i32): Param
  ensures typeof(result) == i32_type()
  ensures concrete_i32(result) == self

function concrete_i32(snap: Param): i32
  ensures generic_i32(result) == snap
```]

On permissions, a pair of bodyless methods exchanges #vi[`p_i32`] for
#vi[`p_Param`] and back, relating the two snapshots through #vi[`old`]. These
pairs are the only cycles anywhere in the generated program. Neither function has
a body, so the cycle runs through their contracts.

#para[Loops] A loop is a back edge in the block graph rather than a
#vi[`while`]. The label heading the loop carries the invariant, written as one
#vi[`invariant`] clause per permission. For an unannotated program that
invariant states the permissions the loop holds on to and nothing about the
values in them.

#para[Borrows] A borrow that outlives the statement creating it becomes a magic
wand. Prusti reads the borrow checker's record of where each borrow ends, and
emits a wand giving the permission back at that point. A function returning a
mutable reference into its argument states the wand in its postcondition.

#no-numbers[```viper
ensures acc(p_Param(res.target, i32_type()), write) --*
        acc(p_Param(old(arg).target, Point_type()), write)
```]

The caller receives permission to the returned reference together with the wand.
Applying the wand trades that permission back for permission to the whole
structure, which is how the encoding models the borrow ending. The method proves
the wand in a #vi[`package`] block that folds the structure back up and runs the
casts above. A labelled #vi[`old`] names the state each borrow was taken in.

These constructs delimit the fragment of Viper that a spec-less Rust program
needs, and that this work sets out to support:

- *Methods:* goto-based control flow over flat basic-block graphs, with
  conditional jumps, back edges, invariants on a loop head, and bodyless methods
  carrying contracts. #vi[`old`] appears in postconditions, and only there.
- *Functions:* abstract and heap-dependent, with permission preconditions and
  #vi[`unfolding`] in their bodies, and mutually recursive definitions relating
  concrete and erased snapshots.
- *Predicates:* #vi[`fold`], #vi[`unfold`], abstract predicates, and bodies
  whose permissions are guarded by conditions on the heap.
- *Domains and ADTs:* non-generic domains whose axioms use #vi[`forall`], every
  one with an encoder-supplied trigger, and algebraic data types with
  constructors, destructors and discriminants, among them the type reifying the
  crate's types.
- *Base Viper:* full and wildcard permission amounts, amounts that are
  conditional expressions rather than literals, the arithmetic operators, and
  #vi[`exhale`] of #vi[`false`] to discharge an unreachable block.

Quantified permissions never appear,
since ownership of an unbounded structure is expressed by a recursive predicate
rather than by a quantifier over locations. Nor do the existential quantifier,
fractional permission literals, or the sequence, set, map and multiset types.
Magic wands appear only in the borrow-returning shape above, and a program
returning no references out of its arguments needs none.


