#import "../macros.typ": *

== Motivation

The _Viper_ project @viper provides a modern intermediate verification language
and a suite of tools, designed for encoding a rich variety of
real-world verification problems down to a set of core verification
primitives. Front-end tools for languages such as Rust, Python, Java,
and Go encode their source programs into Viper, which then discharges
the resulting proof obligations to establish correctness properties
such as memory safety or functional correctness.

Internally, Viper offers two verification backends: _Silicon_ @silicon, based on
symbolic execution, and _Carbon_, based on verification condition
generation. Both ultimately delegate their reasoning to an SMT solver.
Given the breadth of Viper's feature set, these backends are necessarily
intricate: they must handle the general case, and consequently do not
specialize for the cases that dominate in practice.

The proof obligations a front-end generates fall into two groups. The
first are the user-defined *functional specifications*: the assertions a
programmer writes to state what a program computes. The second is the
*core proof*, the fundamental set of obligations required to establish a
program's memory safety and ownership invariants. The two differ sharply
in character. Functional specifications are arbitrary first-order
assertions, and reasoning about them may require arithmetic, quantifiers,
and rich theories. Core proofs are not arbitrary at all — for Rust
programs translated by the _Prusti_ front-end @prusti, they are
automatically inferred from Rust's own memory semantics and are therefore
highly structured. They establish that ownership is respected, that
permissions to memory locations are held where those locations are
accessed, and that permissions are correctly transferred across function
boundaries. Reasoning about them is largely a matter of tracking which
heap locations are known to be equal and which permissions are currently
held.

This distinction matters because the core proof is what dominates in
practice. A Rust program carrying no functional specification at all
still generates a complete core proof, and it is exactly this case that
existing backends discharge through a general-purpose SMT solver — doing
considerably more work than the problem requires. The core premise of
this thesis is that specialized _equality reasoning_ is sufficient to
discharge core proofs, and can do so substantially faster. Functional
specifications, which genuinely require the reasoning power of an SMT
solver, are left outside the scope of this work.

== Problem Statement

// TODO: tighten once evaluation numbers are in.

This thesis addresses the following question: to what extent can the core
proofs generated by _Prusti_ be discharged by equality reasoning alone,
and what performance benefit does doing so yield over the existing
SMT-based Viper backends?

Answering this requires addressing three sub-problems:

+ *Isolating the core.* Viper's surface language is large, and much of
  its complexity is syntactic sugar over a smaller set of primitives.
  A backend that reasons directly over Viper inherits that complexity,
  and every backend must independently reimplement the logic to resolve
  the same high-level constructs. The core verification primitives must
  first be separated out from the features that can be desugared into
  them.

+ *Deciding the core by equality reasoning.* The isolated primitives must
  be shown to be decidable by equality reasoning, and an implementation
  must be built that does so efficiently.

+ *Delimiting the boundary.* Equality reasoning is not a complete
  decision procedure for everything a Viper program may express. The
  point at which it becomes insufficient must be characterized, so that
  the obligations requiring heavier machinery can be identified.

== Contributions

This thesis makes two main contributions:

- *A lower-level verification IR*, called _VMIR_ (Viper Mid-level
  Intermediate Representation), which decomposes Viper's high-level
  features into a smaller core set of verification primitives. VMIR is
  designed to be explicit and minimal rather than human-readable: it
  makes permission amounts and heap states explicit, and desugars
  constructs such as method calls into sequences of primitives. By
  performing this decomposition once, VMIR allows the verification
  backend itself to remain substantially simpler than one operating on
  Viper directly.

- *An equality-reasoning backend* for VMIR. The backend is a symbolic
  execution engine, architecturally inspired by _Silicon_ @silicon, but
  it uses equality saturation over e-graphs — via the _egg_ library
  @egg — as its sole reasoning engine. No SMT solver is involved at any
  point: equality reasoning replaces it outright for the fragment the
  backend supports.

Two properties of this design account for the resulting speedup. First,
obligations are discharged without ever invoking an SMT solver, avoiding
not only the cost of solving but the per-query overhead of constructing a
solver context and translating constraints into it. Second, the backend
does not fully fork its execution state at every branch the way Silicon
does, so branching code does not incur the duplicated work that path-wise
exploration entails.

The backend supports the core feature set of Viper, but this support is
deliberately incomplete. Branching control flow is supported, but back
edges are not, so loops fall outside the supported fragment; magic wands
and quantified permissions are likewise unsupported. Functional
specifications are out of scope: the backend targets core proofs, and
falling back to an SMT solver for obligations beyond its reach is left as
future work rather than implemented here. Within the supported fragment,
the backend discharges Prusti-generated core proofs considerably faster
than Silicon while preserving its verification outcomes. We evaluate this
on TODO(benchmark suite), establishing soundness by regression against
Silicon and measuring a TODO(speedup) reduction in end-to-end
verification time.

== Thesis Outline

@sec:background introduces Viper, the Prusti front-end, and equality
reasoning via equality saturation. @sec:approach presents VMIR and the
design of the equality-reasoning backend. @sec:implementation describes
the implementation, and @sec:results evaluates it against Silicon, both
for soundness and for performance. @sec:future-work concludes and
discusses directions for extending the supported fragment.
