#import "../macros.typ": *
#import "../generated/perf-rust-scalars.typ": *
#import "../generated/perf-viper-scalars.typ": *

= Introduction

The Viper project at ETH Zurich @viper provides an intermediate verification
language and a toolchain that map a range of real-world verification tasks onto
a shared set of core primitives. Frontends for Rust, Python, Go and Java encode
their source programs into Viper, which then discharges the resulting
obligations to establish properties such as memory safety or functional
correctness.

Internally Viper offers two backends, Silicon @silicon by symbolic execution and
Carbon @carbon by verification condition generation, and both ultimately hand
their reasoning to an SMT solver. Because Viper supports a broad feature set,
both backends are necessarily intricate: they handle the general case, and do
not specialise for the case that dominates in practice.

The proof obligations a frontend produces fall into two groups, and the split
runs by who writes them. A _functional specification_ is written by a person and
states what a program computes. It is an arbitrary first-order assertion, and proving one may
take arithmetic, quantifiers and rich theories, which is work only a solver can
do. A _core proof_ is generated by the frontend from the source language's memory
and ownership semantics. It states that a permission is held wherever memory is
accessed, that ownership transfers correctly across a call, and that a
structure's invariant is re-established before it is handed on.

Rust makes the second kind interesting. Its type system already establishes that
a value is either shared or mutable but never both, and the borrow checker
settles that statically. The Prusti frontend @prusti therefore derives a
program's whole core proof from the program text, without a line
of annotation. A Rust program that specifies nothing at all still yields a
complete core proof, so this is the common case rather than a corner of it.

Such a proof asks a narrow question. The same location acquires many spellings
over an execution, as values are copied and snapshots taken. Establishing that a
permission is held where the program reads memory therefore means establishing
that two of those spellings agree. Permission amounts work the same way: a
caller that passes a fraction $p$ keeps $1 - p$, and must recover
$(1 - p) + p = 1$ when the callee returns it. Both are equalities between
applications of uninterpreted symbols, and settling them takes no theory and no
case split.

A general-purpose SMT solver therefore brings more machinery than the question
uses. Every obligation becomes a query, translated into the solver's language
and answered across a process boundary by a search built for arbitrary theories.
This thesis holds that equality reasoning alone settles the core proof of a
spec-less program, and settles it faster.

This thesis makes two contributions.

+ *A mid-level verification representation.* VMIR, the Viper Mid-level
  Intermediate Representation, decomposes Viper's high-level features into a
  smaller set of verification primitives. It is explicit rather than readable:
  permission amounts and heap states are named operands, a field and a predicate
  instance are one kind of heap location, and a method call, a fold and an unfold
  are sequences of primitives rather than constructs of their own. Performing
  that decomposition once lets the backend behind it stay considerably simpler than
  one processing Viper directly.

+ *An equality-reasoning backend.* Helium executes VMIR symbolically, in the
  manner of Silicon, but uses equality saturation over e-graphs as its only
  reasoning engine, through the _egg_ library @egg. No SMT solver is involved at
  any point. Two properties of the design account for the speed. Obligations are
  answered from the e-graph, so nothing pays the cost of building a query,
  translating it and waiting on another process. Execution does not branch at a
  conditional, so the work after a branch is done once rather than once per path.

We evaluate Helium against Silicon on #rust-files Prusti encodings and
#viper-files hand-written Viper programs. The two agree on every declaration
both accept, and no run of ours is vacuous. Helium reduces total verification
time on the Prusti corpus by #rust-ratio-total, with a geometric mean of
#rust-ratio-geo per file. The advantage is not uniform. It is largest on
straight-line code, where facts accumulate with no branch to reconcile, and it
disappears on heap-heavy branching code, where the single state Helium carries
has to reconcile conditional permission amounts at every join.
