#import "../macros.typ": *

= Approach <sec:approach>

The primary goal of this work is to accelerate the verification of programs with
highly structured proof obligations, ones that can be closed with relatively simple
equality reasoning. For instance, the core proof generated by the Prusti frontend
@prusti for Rust programs generates a large number of bookkeeping obligations that
mirror the memory safety and ownership guarantees of Rust. These obligations are highly
structured and should not require a general-purpose SMT solver to discharge.

In order to achieve faster verification, we propose a new verification pipeline that
contributes two components: a new IR -- Viper Mid-Level Intermediate Representation
(VMIR for short), and a new verification backend, which we give the name Helium.

== VMIR: Viper Mid-Level Intermediate Representation <sec:impl-vmir>

Viper is a highly expressive language designed to be read and written by humans.
Consequently, it incorporates syntactic sugar to improve readability and ease
of programming. However, this is not ideal from a verification perspective, as
the verifier must be more complex to handle the large feature set of Viper.

We propose a smaller, more focused intermediate representation. VMIR simplifies
the verification process by modifying several key aspects of Viper:

- *Explicit Semantics:* All syntactic sugar is eliminated. For example, in
  surface Viper, access expressions like #vi[`acc(x.f)`] carry an implicit
  permission amount of #vi[`write`]. VMIR removes these assumptions, requiring all
  such details to be stated explicitly.

- *Self-Contained Representation:* While Silicon @silicon relies on the Silver
  project @silver to resolve implicit details, our verifier cannot directly
  depend on it due to the programming language boundary. Because VMIR explicitly
  encodes all semantics, it serves as a fully self-contained textual format,
  allowing any external verifier to process it independently.

- *Reduced Operator Set:* VMIR retains only a single boolean connective: the
  ternary operator. As a result, #vi[`a && b`] is rewritten as #vm[`a ? b : false`],
  and #vi[`a || b`] becomes #vm[`a ? true : b`]. This ensures there is only one
  canonical way to represent an expression.

- *Explicitly Typed Temporaries:* To simplify reasoning, VMIR eliminates mutable
  variables. This shifts the focus to the values themselves rather than their changes
  over time. It also flattens nested expressions, assigning every subexpression
  to an explicitly typed temporary. Consequently, the representation naturally
  assumes a Static Single Assignment (SSA) form.

- *Explicit Heap State:* In Viper, the heap has a temporal nature. Reading a
  field #vi[`x.f`] implicitly reads from the current heap, while #vi[`old(..)`]
  evaluates expressions in some earlier version of the heap. In VMIR, the heap is
  treated as a special, explicit value that instructions produce and consult.

- *Unified Heap Objects:* VMIR unifies the concepts of predicates and fields.
  While Silicon treats fields and predicates stored in the heap separately,
  storing a predicate instance in VMIR is equivalent to storing an ADT instance
  that describes the predicate's footprint. This allows the verifier to reason
  about all heap objects uniformly.

- *Generalised Declarations:* Several Viper constructs share one shape, and VMIR
  gives that shape a single declaration form rather than one form each. A
  predicate, a method contract and a function precondition all bundle heap
  permissions with a claim about them, so all three lower to the same VMIR
  declaration. The verifier implements that form once and reuses it wherever a
  frontend reaches for any of the three.

- *Instruction Decomposition:* VMIR breaks down Viper's complex operations into
  a minimal set of core instructions. For instance, a method call is decomposed
  into two distinct instructions: exhaling the precondition resource, and inhaling
  the postcondition. Similarly, a predicate fold is exactly equivalent to exhaling
  the predicate body and adding a heap chunk representing the folded predicate.

Each of these design decisions supports a backend that reasons by equality. A single canonical form per expression ensures that equal terms are structurally identical, allowing the backend to observe equalities without derivation. Immutable temporaries prevent terms from changing state, simplifying equality tracking. An explicit heap represents state as just another term, unifying stateful and stateless reasoning within the same structure. Instruction decomposition reduces the surface area of the verifier: Helium implements a minimal set of primitives, with each serving multiple high-level Viper constructs.

Initially, VMIR is designed to only be lowered directly from Viper. In its design
it is, however, intended to provide a representation that could be used directly
by a frontend like Prusti
in order to take advantage of increased expressiveness, at the cost of a more
complex frontend and fewer correctness guarantees.

== The Helium Verifier

Following the lowering into VMIR, verification is handed to Helium, our novel backend. Helium is designed as a symbolic execution verifier inspired by Silicon, mirroring its implementation and design where practical, but deliberately diverging to exploit the structured nature of the proof obligations generated by frontends like Prusti. Rather than mapping intermediate constructs directly into SMT solver queries, Helium employs equality reasoning to discharge obligations with minimal computational effort.

This approach is motivated by the nature of the obligations: bookkeeping tasks frequently ask whether two existing terms are equal, a problem efficiently solved by congruence closure. Helium uses an e-graph to manage this: it stores all generated terms, records discovered equalities, and automatically computes their congruence closure. Since a single method body generates numerous obligations over a shared set of terms, a single e-graph per method avoids redundant computation. In contrast, SMT-based backends must translate constraints and rebuild solver contexts for each individual query.

Helium, implemented using the Rust egg library @egg, maintains an e-graph as its core state representation. Equivalences are established by congruence closure and a limited set of simplifying rewrite rules. To prevent exponential path explosion, Helium does not branch its e-graph at a conditional, ensuring that work is not needlessly duplicated.

Obligations are discharged using a tiered approach: fast, structural checks are attempted before more expensive reasoning mechanisms, keeping the common case efficient.

Helium prioritizes speed over completeness and does not rely on an SMT solver. Obligations that cannot be resolved structurally, such as those involving complex functional specifications, are currently out of scope. Falling back to a general-purpose solver like Z3 is left as future work.
