#import "../macros.typ": *

= Approach <sec:approach>

The primary goal of this work is to accelerate the verification of programs with
highly structured proof obligations, ones that can be closed with relatively simple
equality reasoning. For instance, the core proof generated by the Prusti frontend
@prusti for Rust programs generates a large number of bookkeeping obligations that
mirror the memory safety and ownership guarantees of Rust. These obligations are highly
structured and should not require a general-purpose SMT solver to discharge.

In order to achieve faster verification, we propose a new verification pipeline that
contributes two components: a new IR -- Viper Mid-Level Intermediate Representation
(VMIR for short), and a new verification backend, which we give the name Helium.

== VMIR: Viper Mid-Level Intermediate Representation <sec:impl-vmir>

Viper is a highly expressive language designed to be read and written by humans.
Consequently, it incorporates syntactic sugar to improve readability and ease
of programming. However, this is not ideal from a verification perspective, as
the verifier must be more complex to handle the large feature set of Viper.

We propose a smaller, more focused intermediate representation. VMIR simplifies
the verification process by modifying several key aspects of Viper:

- *Explicit Semantics:* All syntactic sugar is eliminated. For example, in
  surface Viper, access expressions like #vi[`acc(x.f)`] carry an implicit
  permission amount of #vi[`write`]. VMIR removes these assumptions, requiring all
  such details to be stated explicitly.

- *Self-Contained Representation:* While Silicon @silicon relies on the Silver
  project @silver to resolve implicit details, our verifier cannot directly
  depend on it due to the programming language boundary. Because VMIR explicitly
  encodes all semantics, it serves as a fully self-contained textual format,
  allowing any external verifier to process it independently.

- *Reduced Operator Set:* VMIR retains only a single boolean connective: the
  ternary operator. As a result, #vi[`a && b`] is rewritten as #vm[`a ? b : false`],
  and #vi[`a || b`] becomes #vm[`a ? true : b`]. This ensures there is only one
  canonical way to represent an expression.

- *Explicitly Typed Temporaries:* To simplify reasoning, VMIR eliminates mutable
  variables. This shifts the focus to the values themselves rather than their changes
  over time. It also flattens nested expressions, assigning every subexpression
  to an explicitly typed temporary. Consequently, the representation naturally
  assumes a Static Single Assignment (SSA) form.

- *Explicit Heap State:* In Viper, the heap has a temporal nature. Reading a
  field #vi[`x.f`] implicitly reads from the current heap, while #vi[`old(..)`]
  evaluates expressions in some earlier version of the heap. In VMIR, the heap is
  treated as a special, explicit value that instructions produce and consult.

- *Unified Heap Objects:* VMIR unifies the concepts of predicates and fields.
  While Silicon treats fields and predicates stored in the heap separately,
  storing a predicate instance in VMIR is equivalent to storing an ADT instance
  that describes the predicate's footprint. This allows the verifier to reason
  about all heap objects uniformly.

- *Generalised Declarations:* Several Viper constructs share one shape, and VMIR
  gives that shape a single declaration form rather than one form each. A
  predicate, a method contract and a function precondition all bundle heap
  permissions with a claim about them, so all three lower to the same VMIR
  declaration. The verifier implements that form once and reuses it wherever a
  frontend reaches for any of the three.

- *Instruction Decomposition:* VMIR breaks down Viper's complex operations into
  a minimal set of core instructions. For instance, a method call is decomposed
  into two distinct instructions: exhaling the precondition resource, and inhaling
  the postcondition. Similarly, a predicate fold is exactly equivalent to exhaling
  the predicate body and adding a heap chunk representing the folded predicate.

Each of these design decisions supports a backend that reasons by equality. A single canonical form per expression ensures that equal terms are structurally identical, allowing the backend to observe equalities without derivation. Immutable temporaries prevent terms from changing state, simplifying equality tracking. An explicit heap represents state as just another term, unifying stateful and stateless reasoning within the same structure. Instruction decomposition reduces the surface area of the verifier: Helium implements a minimal set of primitives, with each serving multiple high-level Viper constructs.

Initially, VMIR is designed to only be lowered directly from Viper. In its design
it is, however, intended to provide a representation that could be used directly
by a frontend like Prusti
in order to take advantage of increased expressiveness, at the cost of a more
complex frontend and fewer correctness guarantees.

== The Helium Verifier

Following the lowering into VMIR, verification is handed to Helium, our novel backend. Helium is designed as a symbolic execution verifier inspired by Silicon, mirroring its implementation and design where practical, but deliberately diverging to exploit the structured nature of the proof obligations generated by frontends like Prusti. Rather than mapping intermediate constructs directly into SMT solver queries, Helium employs equality reasoning to discharge obligations with minimal computational effort.

This approach is motivated by the nature of the obligations: bookkeeping tasks frequently ask whether two existing terms are equal, a problem efficiently solved by congruence closure. Helium uses an e-graph to manage this: it stores all generated terms, records discovered equalities, and automatically computes their congruence closure. Since a single method body generates numerous obligations over a shared set of terms, a single e-graph per method avoids redundant computation. In contrast, SMT-based backends must translate constraints and rebuild solver contexts for each individual query.

Helium, implemented using the Rust egg library @egg, maintains an e-graph as its core state representation. Equivalences are established by congruence closure and a limited set of simplifying rewrite rules. To prevent exponential path explosion, Helium avoids fully forking its e-graph at branches, ensuring that work is not needlessly duplicated.

Obligations are discharged using a tiered approach: fast, structural checks are attempted before more expensive reasoning mechanisms, keeping the common case efficient.

Helium prioritizes speed over completeness and does not rely on an SMT solver. Obligations that cannot be resolved structurally---such as those involving complex functional specifications---are currently out of scope. Falling back to a general-purpose solver like Z3 is left as future work.

== Establishing the Minimal Supported Feature Set

While VMIR and Helium efficiently handle structured obligations, building a complete verifier for Viper is a substantial undertaking. To focus our efforts, we establish the boundaries of a minimal supported fragment. We derive this fragment by examining the obligations generated by a representative Rust program. The following example contains no hand-written specifications; every obligation stems entirely from Prusti encoding Rust's inherent safety guarantees.

#rust(
  caption: [A representative Rust program exercising the constructs Prusti emits.],
  label: "lst:example-rust",
)[```rust
pub struct Account {
    pub balance: i32,
    pub limit: i32,
}

pub enum Transaction {
    Deposit(i32),
    Withdrawal(i32),
}

pub enum AccountList {
    Empty,
    Cons(Account, Box<AccountList>),
}

pub fn account_deposit(a: &mut Account, amount: i32) {
    if 0 < amount {
        a.balance = a.balance + amount;
    }
}

pub fn account_apply(a: &mut Account, t: &Transaction) {
    match t {
        Transaction::Deposit(amount) => {
            a.balance = a.balance + *amount;
        }
        Transaction::Withdrawal(amount) => {
            a.balance = a.balance - *amount;
        }
    }
}

pub fn sum_balances(list: &AccountList) -> i32 {
    let mut total = 0;
    let mut cur = list;
    while let AccountList::Cons(a, rest) = cur {
        total = total + a.balance;
        cur = rest;
    }
    total
}
```]

Prusti compiles these six declarations into 1,774 lines of Viper, encompassing domains, ADTs, predicates, and functions. Instead of a line-by-line analysis, we focus on the core verification challenges introduced by this encoding. For readability, identifiers and discriminant comparisons in the Viper snippets below have been simplified.

Simple structs like #ru[`Account`] are represented using algebraic datatypes for snapshots and predicates (e.g., #vi[`own_Account`]) for permissions. Accessing field values requires heap-dependent functions containing #vi[`unfolding`] expressions. Recursive structures like #ru[`AccountList`] introduce recursion via the #ru[`Box`] type. Prusti encodes this without relying on Viper's generics, instead reifying types into a dedicated #vi[`Type`] datatype and using abstract predicates linked by bodyless methods. This type erasure also applies to snapshots. Casting between a concrete snapshot and its generic representation necessitates mutually recursive function definitions. Each type receives a pair of bodyless functions for casting in both directions, constrained only by postconditions asserting that the operations are inverses. These pairs form the only cycles in the program, requiring Helium to support cyclic function dependencies.

Rust functions are translated into flat control-flow graphs using #vi[`goto`] and #vi[`label`] instructions. Loops are represented purely as back edges rather than structured #vi[`while`] constructs. Consequently, the permissions held at any basic block depend conditionally on the execution path, tracked via boolean variables representing edge traversals. Arithmetic operations are encoded separately as functions over snapshots, relying on integer domains with custom axioms and encoder-supplied triggers.

Enums like #ru[`Transaction`] introduce discriminants. The corresponding generated predicate ensures the discriminant matches a known variant and conditionally grants permission to the active payload (@lst:example-discr).

#viper(
  caption: [The predicate for #ru[`Transaction`]. The disjunction states that the two variants exhaust the type, and each payload permission is guarded by the discriminant that selects it.],
  label: "lst:example-discr",
)[```viper
predicate own_Transaction(self: Ref) {
  acc(own_isize(Transaction_field_discr(self)), write) &&
  (let d == (isize_value(snap_isize(Transaction_field_discr(self)))) in
     (d == 0 || d == 1) &&
     (d == 0 ==> acc(own_Transaction_0(self), write)) &&
     (d == 1 ==> acc(own_Transaction_1(self), write)))
}
```]

Pattern matching on enums, as seen in the #ru[`account_apply`] function, combines this control flow with conditional permissions (@lst:example-match). The block reads the discriminant, exhales the permission borrowed to read it, and branches accordingly. Each arm sets a boolean flag for the edge it traverses and jumps to the corresponding block. As a result, all #vi[`fold`] and #vi[`unfold`] operations in subsequent blocks are guarded by these path conditions.

#viper(
  caption: [The #ru[`match`] of #ru[`account_apply`] as a statement. Each arm records the edge it takes and jumps to the block implementing it. The arm no variant selects exhales #vi[`false`], which is where exhaustiveness is discharged.],
  label: "lst:example-match",
)[```viper
label bb_0
// _3p holds the discriminant of *t, read out of the enum's predicate
d := snap_isize(_3p)
exhale acc(own_isize(_3p), write)
if (isize_value(d) == 0) {
  _from_bb0_to_bb2 := true
  goto bb_2
} elseif (isize_value(d) == 1) {
  _from_bb0_to_bb3 := true
  goto bb_3
} else {
  _from_bb0_to_bb1 := true
  goto bb_1
}

label bb_1
exhale false
inhale false
goto end
```]

The exhaustiveness fall-through arm is particularly interesting. In Rust, even a #ru[`match`] used as a statement evaluates to a value---here, the unit type #ru[`()`]. The #ru[`account_apply`] function implicitly returns this unit type, which Prusti encodes as a heap-value that must be exhaled upon method return. The unreachable arm, however, does not construct this value. Instead, Prusti marks the path as dead by emitting an #vi[`exhale false`]. Helium must therefore reason that all live execution branches successfully construct the required heap value, and correctly dismiss dead branches as unreachable.

Collecting these requirements defines the *minimal supported feature set* for VMIR and Helium:

- *Methods:* goto-based control flow over flat basic-block graphs, with
  conditional jumps, back edges, and bodyless methods carrying contracts.
  #vi[`old`] appears in postconditions, and only there.
- *Functions:* abstract and heap-dependent, with permission preconditions and
  #vi[`unfolding`] expressions in their bodies. Mutually recursive definitions
  are used to cast between concrete and generic snapshots.
- *Predicates:* #vi[`fold`], #vi[`unfold`], abstract predicates, and predicate
  bodies whose permissions are guarded by conditions on the heap.
- *Heap:* full and wildcard permission amounts, and permission amounts that are
  conditional expressions rather than literals. The program above holds only
  #vi[`write`]. Wildcard permissions are used to encode any of the heap dependent
  functions.
- *Domains:* non-generic domains carrying axioms that rely on the #vi[`forall`]
  quantifier, every one of them with a trigger supplied by the encoder.
- *ADTs:* algebraic datatypes with constructors, destructors and discriminants,
  among them the datatype whose values reify the crate's types. No declaration
  needs type parameters of its own, because that datatype is what the encoding
  erases Rust's generics into.
- *Base Viper:* the arithmetic operators #vi[`+`], #vi[`-`], #vi[`*`],
  #vi[`/`] and #vi[`%`], and #vi[`exhale`] of #vi[`false`] to discharge an
  unreachable block.

This enumeration is as important for what it omits as for what it includes. It excludes fractional permission literals, magic wands, quantified permissions, and sequence, set, or map abstractions. This minimal feature set strictly bounds the scope of this work and directly motivates the architecture of the new verification pipeline.

