#import "../macros.typ": *

The primary goal of this work is to accelerate the verification of programs generated by the Prusti frontend. Prusti translates Rust programs into Viper, generating a vast number of bookkeeping obligations—framing permissions, managing fold and unfold operations, and establishing structural well-formedness. Traditional verification backends, which are designed as general-purpose engines supporting the entirety of the Viper language, often struggle with the sheer volume of these highly structural, repetitive proof obligations.

Rather than building another general-purpose verifier, our approach is to tailor the entire verification pipeline—from the intermediate representation down to the proving engine—specifically to the fragment of Viper that Prusti actually emits. By shedding the weight of unsupported features, we can construct a pipeline optimized for throughput on core structural proofs.

== A Guiding Example

To establish the boundaries of this supported fragment, we consider a representative Rust program. The following example contains no hand-written specifications; every obligation it generates stems entirely from Prusti encoding Rust's own safety guarantees.

#rust(caption: [A representative Rust program exercising the constructs Prusti emits.], label: "lst:example-rust")[```rust
pub struct Account {
    pub balance: i32,
    pub limit: i32,
}

pub enum Transaction {
    Deposit(i32),
    Withdrawal(i32),
}

pub enum AccountList {
    Empty,
    Cons(Account, Box<AccountList>),
}

pub fn account_deposit(a: &mut Account, amount: i32) {
    if 0 < amount {
        a.balance = a.balance + amount;
    }
}

pub fn account_apply(a: &mut Account, t: &Transaction) {
    match t {
        Transaction::Deposit(amount) => {
            a.balance = a.balance + *amount;
        }
        Transaction::Withdrawal(amount) => {
            a.balance = a.balance - *amount;
        }
    }
}

pub fn sum_up_to(n: i32) -> i32 {
    let mut i = 0;
    let mut total = 0;
    while i < n {
        total = total + i;
        i = i + 1;
    }
    total
}

pub fn sum_balances(list: &AccountList) -> i32 {
    let mut total = 0;
    let mut cur = list;
    while let AccountList::Cons(a, rest) = cur {
        total = total + a.balance;
        cur = rest;
    }
    total
}
```]

When Prusti compiles this crate, it outputs thousands of lines of Viper to model the state and ownership of these types. Instead of analyzing that generated output line by line, we can summarize the constructs it exercises. This establishes the *minimal supported feature set* that Helium must handle:

- *Methods:* goto-based control flow. (Prusti emits flat basic-block graphs rather than structured #vi[`while`] loops).
- *Functions:* recursive, abstract, functions with a body, and heap-dependent functions.
- *Predicates:* fold, unfold, unfolding expressions, and abstract predicates.
- *Heap:* wildcard permissions, realistically appearing only in functions and at most within unfolding expressions.
- *Domains:* non-generic domains, carrying axioms that rely on the #vi[`forall`] quantifier.
- *Base Viper:* the majority of arithmetic operators (#vi[`+`], #vi[`-`], #vi[`*`], #vi[`/`], #vi[`%`]).
- *ADTs:* simple algebraic datatypes; no generics are required.

This enumeration is as important for what it includes as for what it omits. There are no fractional permission literals, no magic wands, no quantified permissions, and no sequence or set abstractions. This minimal feature set strictly bounds our scope and directly motivates the implementation of our new pipeline.

== System Design

To achieve high-performance verification over this specific feature set, we rethink both how the program is represented and how its obligations are proven.

=== VMIR: Viper Mid-Level Intermediate Representation <sec:impl-vmir>

Viper is a highly expressive language designed to be read and written by humans. Consequently, it incorporates syntactic sugar to improve readability and ease of programming. However, this is not ideal from a verification perspective, as the verifier must continually account for all implicit semantics in the surface language.

We propose a smaller, more focused intermediate representation, which we call VMIR (Viper Mid-Level Intermediate Representation). VMIR simplifies the verification process by modifying several key aspects of Viper:

- *Explicit Semantics:* All syntactic sugar is eliminated. For example, in surface Viper, access expressions like #vi[`acc(x.f)`] carry an implicit permission amount of #vi[`write`]. VMIR removes these assumptions, requiring all such details to be stated explicitly.

- *Self-Contained Representation:* While Silicon @silicon relies on the Silver project @silver to resolve implicit details, our verifier cannot directly depend on it due to the programming language boundary. Because VMIR explicitly encodes all semantics, it serves as a fully self-contained textual format, allowing any external verifier to process it independently.

- *Reduced Operator Set:* VMIR retains only a single boolean connective: the ternary operator. As a result, #vi[`a && b`] is rewritten as #vm[`a ? b : false`], and #vi[`a || b`] becomes #vm[`a ? true : b`]. This ensures there is only one canonical way to represent an expression.

- *Explicitly Typed Temporaries:* To simplify reasoning, VMIR eliminates mutable variables. This shifts the focus to the values themselves rather than their changes over time. It also flattens nested expressions, assigning every subexpression to an explicitly typed temporary. Consequently, the representation naturally assumes a Static Single Assignment (SSA) form.

- *Explicit Heap State:* In Viper, the heap has a temporal nature. Reading a field #vi[`x.f`] implicitly reads from the current heap, while #vi[`old(..)`] evaluates expressions in some earlier version of the heap. In VMIR, the heap is treated as a special, explicit value that instructions produce and consult.

- *Unified Heap Objects:* VMIR unifies the concepts of predicates and fields. While Silicon treats fields and predicates stored in the heap separately, storing a predicate instance in VMIR is equivalent to storing an ADT instance that describes the predicate's footprint. This allows the verifier to reason about all heap objects uniformly.

- *Instruction Decomposition:* VMIR breaks down Viper's complex operations into a minimal set of core instructions. For instance, a method call is decomposed into two distinct instructions: exhaling the precondition resource, and inhaling the postcondition. Similarly, a predicate fold is exactly equivalent to exhaling the predicate body and adding a heap chunk representing the folded predicate.

=== The Helium Verifier

The verifier itself, which we call Helium, is built to consume VMIR and rapidly discharge the structural obligations that dominate Prusti's output.

We set a deliberate expectation on Helium's proving power: it is designed to be exceptionally fast at bookkeeping and structural reasoning. It is not designed to prove complex functional specifications that require deep case-splitting or non-linear arithmetic. If an obligation falls outside this structural core, Helium faithfully records the unproven state rather than attempting expensive fallback strategies.

To achieve this, Helium is implemented entirely in Rust. At its core, it represents the symbolic state using an e-graph, heavily leveraging the `egg` library. E-graphs excel at fast, saturation-based equality reasoning. Crucially, the base version of Helium uses no SMT solver whatsoever. By avoiding the overhead of translating state to an external solver and waiting for a generalized decision procedure, Helium maximizes throughput on the specific fragment of Viper it was built to handle.
